language: php

php:
  - 5.3

before_script:
  - mysql -e 'create database mustached_test;'
  - php oil refine db:setup_test

script: php oil test

notifications:
  email:
    recipients:
      - jeremie.pottier+mustached@gmail.com
    on_success: change
    on_failure: change